/**
 * ならやさしいイベントナビ v5 - イベントデータ
 * 更新日: 2025-12-14
 * 新機能: ⑤盲導犬・介助犬・聴導犬同伴可の情報追加
 */

// イベントデータ（28件）
const EVENTS_DATA = [
    // 元からあったイベント（日付を2025年12月以降に変更）
    {
        id: 1,
        name: "奈良公園クリスマスイベント",
        date: "2025-12-14",
        time: "10:00~16:00",
        category: "文化・イベント",
        venue: "奈良公園",
        address: "奈良県奈良市雑司町469",
        lat: 34.684915,
        lon: 135.842827,
        description: "奈良公園でクリスマスイベントを開催します。鹿とのふれあいや音楽イベントなど、家族で楽しめるプログラムが盛りだくさん。",
        accessibility: ["多目的トイレ", "段差への対応", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良公園管理事務所 0742-22-0375",
        capacity: "制限なし",
        fee: "無料"
    },
    {
        id: 2,
        name: "奈良市美術館 新春展覧会",
        date: "2026-01-05",
        time: "09:00~17:00",
        category: "美術・展示",
        venue: "奈良市美術館",
        address: "奈良県奈良市二条大路南1-3-1",
        lat: 34.685235,
        lon: 135.802094,
        description: "新春を祝う日本画と書道の特別展覧会。地元作家の作品を中心に展示します。",
        accessibility: ["多目的トイレ", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市美術館 0742-30-1510",
        capacity: "200名",
        fee: "一般500円、高校生以下無料"
    },
    {
        id: 3,
        name: "春日大社 節分祭",
        date: "2026-02-03",
        time: "11:00~15:00",
        category: "文化・イベント",
        venue: "春日大社",
        address: "奈良県奈良市春日野町160",
        lat: 34.681274,
        lon: 135.848257,
        description: "春日大社の伝統的な節分祭。豆まきや御祈祷が行われます。",
        accessibility: ["多目的トイレ", "段差への対応", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "春日大社 0742-22-7788",
        capacity: "制限なし",
        fee: "無料"
    },
    {
        id: 4,
        name: "奈良健康フェスタ 2026",
        date: "2026-03-15",
        time: "10:00~15:00",
        category: "健康・福祉",
        venue: "はぐくみセンター",
        address: "奈良県奈良市三条本町13-1",
        lat: 34.679181,
        lon: 135.817365,
        description: "健康チェックや栄養相談、体操教室など、健康をテーマにした総合イベント。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応", "車椅子貸出", "優先駐車場", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市健康増進課 0742-34-5129",
        capacity: "500名",
        fee: "無料"
    },
    {
        id: 5,
        name: "子育て応援フェア",
        date: "2026-03-22",
        time: "10:00~14:00",
        category: "子育て・教育",
        venue: "奈良市ならまちセンター",
        address: "奈良県奈良市東寺林町38",
        lat: 34.679814,
        lon: 135.830993,
        description: "子育て世代を応援するイベント。育児相談や親子体操、手作りおもちゃ教室など。",
        accessibility: ["多目的トイレ", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市子ども育成課 0742-34-4792",
        capacity: "300名",
        fee: "無料"
    },
    {
        id: 6,
        name: "東大寺 お水取り",
        date: "2026-03-12",
        time: "19:00~",
        category: "文化・イベント",
        venue: "東大寺 二月堂",
        address: "奈良県奈良市雑司町406-1",
        lat: 34.689019,
        lon: 135.839844,
        description: "奈良の春を告げる伝統行事。1250年以上続く火と水の祭典。",
        accessibility: ["段差への対応", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "東大寺 0742-22-5511",
        capacity: "制限なし",
        fee: "無料"
    },
    {
        id: 7,
        name: "奈良マラソン 2025",
        date: "2025-12-08",
        time: "08:30~",
        category: "スポーツ",
        venue: "奈良公園周辺（スタート・ゴール:鴻ノ池陸上競技場）",
        address: "奈良県奈良市法蓮町757-3",
        lat: 34.703037,
        lon: 135.829163,
        description: "世界遺産を走る日本有数のマラソン大会。フルマラソンと10km種目があります。",
        accessibility: ["多目的トイレ", "車椅子貸出", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良マラソン実行委員会 0742-81-8752",
        capacity: "12,000名",
        fee: "フルマラソン10,000円、10km4,000円"
    },
    {
        id: 8,
        name: "奈良若草山焼き 2026",
        date: "2026-01-25",
        time: "18:15~",
        category: "文化・イベント",
        venue: "若草山",
        address: "奈良県奈良市雑司町",
        lat: 34.691254,
        lon: 135.850891,
        description: "奈良の冬の風物詩。山全体に火が放たれ、幻想的な光景が広がります。",
        accessibility: ["段差への対応", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市観光協会 0742-22-3900",
        capacity: "制限なし",
        fee: "無料"
    },
    {
        id: 9,
        name: "奈良 食と農のフェスティバル",
        date: "2025-12-21",
        time: "10:00~16:00",
        category: "食・グルメ",
        venue: "ならでんフィールド（鴻ノ池陸上競技場）",
        address: "奈良県奈良市法蓮町757-3",
        lat: 34.697341,
        lon: 135.828332,
        description: "奈良の特産品や地元農産物の販売、料理教室などを実施。",
        accessibility: ["多目的トイレ", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市農林課 0742-34-5142",
        capacity: "制限なし",
        fee: "入場無料（飲食・物販は有料）"
    },
    {
        id: 10,
        name: "平城宮跡歴史公園 天平たなばた祭り",
        date: "2026-07-05",
        time: "16:00~21:00",
        category: "文化・イベント",
        venue: "平城宮跡歴史公園",
        address: "奈良県奈良市二条大路南3-5-1",
        lat: 34.691074,
        lon: 135.795456,
        description: "平城京の雰囲気を再現した七夕祭り。燈火イベントや音楽演奏など。",
        accessibility: ["多目的トイレ", "段差への対応", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "平城宮跡管理センター 0742-36-8780",
        capacity: "制限なし",
        fee: "無料"
    },
    {
        id: 11,
        name: "奈良シニアいきいきフェスタ",
        date: "2026-02-20",
        time: "10:00~15:00",
        category: "健康・福祉",
        venue: "奈良市北部会館市民文化ホール",
        address: "奈良県奈良市右京1丁目1-4",
        lat: 34.721911,
        lon: 135.790983,
        description: "高齢者の健康と生きがいづくりをテーマにしたイベント。健康チェック、体操教室、趣味の展示など。",
        accessibility: ["多目的トイレ", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市長寿福祉課 0742-34-5439",
        capacity: "500名",
        fee: "無料"
    },
    {
        id: 12,
        name: "新春コンサート 2026",
        date: "2026-01-10",
        time: "14:00~16:00",
        category: "音楽・芸術",
        venue: "奈良市北部会館市民文化ホール",
        address: "奈良県奈良市右京1丁目1-4",
        lat: 34.721911,
        lon: 135.790983,
        description: "新春を祝うクラシックコンサート。地元オーケストラによる演奏。",
        accessibility: ["多目的トイレ", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市北部会館 0742-71-5747",
        capacity: "800名",
        fee: "一般2,000円、高校生以下1,000円"
    },
    {
        id: 13,
        name: "デジタルアート展示会",
        date: "2026-02-01",
        time: "10:00~18:00",
        category: "美術・展示",
        venue: "奈良市北部会館",
        address: "奈良県奈良市右京1丁目1-4",
        lat: 34.707524,
        lon: 135.783516,
        description: "最新のデジタル技術を活用したアート展示。インタラクティブな作品も多数。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応", "車椅子貸出", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市北部会館 0742-71-5747",
        capacity: "200名",
        fee: "一般800円、高校生以下無料"
    },

    // 2025年11月号から追加された新規イベント
    {
        id: 14,
        name: "JNO室内楽シリーズ2025（第3回）",
        date: "2025-11-21",
        time: "19:00~",
        category: "音楽・芸術",
        venue: "学園前ホール",
        address: "奈良県奈良市学園北1-11-4",
        lat: 34.708843,
        lon: 135.777221,
        description: "奈良日本フィルハーモニー管弦楽団メンバーによる室内楽コンサート。車椅子での来場の場合は事前連絡が必要。",
        accessibility: ["多目的トイレ", "エレベータ", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市音楽協会 0742-34-4710",
        capacity: "300名",
        fee: "全席自由 一般2,000円"
    },
    {
        id: 15,
        name: "JNO室内楽シリーズ2025（第4回）",
        date: "2025-12-03",
        time: "19:00~",
        category: "音楽・芸術",
        venue: "奈良100年会館",
        address: "奈良県奈良市三条宮前町7-1",
        lat: 34.681824,
        lon: 135.817337,
        description: "奈良日本フィルハーモニー管弦楽団メンバーによる室内楽コンサート。車椅子での来場の場合は事前連絡が必要。",
        accessibility: ["多目的トイレ", "エレベータ", "車椅子貸出", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市音楽協会 0742-34-4710",
        capacity: "400名",
        fee: "全席指定 一般4,000円"
    },
    {
        id: 16,
        name: "JNO室内楽シリーズ2025（第5回）",
        date: "2025-12-15",
        time: "14:00~",
        category: "音楽・芸術",
        venue: "奈良100年会館",
        address: "奈良県奈良市三条宮前町7-1",
        lat: 34.681824,
        lon: 135.817337,
        description: "奈良日本フィルハーモニー管弦楽団メンバーによる室内楽コンサート。車椅子での来場の場合は事前連絡が必要。",
        accessibility: ["多目的トイレ", "エレベータ", "車椅子貸出", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市音楽協会 0742-34-4710",
        capacity: "400名",
        fee: "全席指定 一般4,000円"
    },
    {
        id: 17,
        name: "男女共同参画市民企画講座「親子で楽しもう！クッキング教室」",
        date: "2025-11-30",
        time: "10:00~13:00",
        category: "子育て・教育",
        venue: "西部公民館",
        address: "奈良県奈良市学園南3-1-5",
        lat: 34.696719,
        lon: 135.75023,
        description: "親子で料理を楽しむクッキング教室。事前申込制で、保育サービス（6か月〜就学前、要事前申込）あり。",
        accessibility: ["多目的トイレ", "エレベータ", "車椅子貸出", "優先駐車場", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "西部公民館 0742-44-0101",
        capacity: "15組",
        fee: "材料費700円"
    },
    {
        id: 18,
        name: "動物愛護フェスティバル",
        date: "2025-11-29",
        time: "10:00~15:00",
        category: "動物・環境",
        venue: "はぐくみセンター1階",
        address: "奈良県奈良市三条本町13-1",
        lat: 34.682551,
        lon: 135.820267,
        description: "動物愛護をテーマにしたイベント。飼育相談、展示、体験コーナーなど。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市保健所 0742-93-8395",
        capacity: "制限なし",
        fee: "無料"
    },
    {
        id: 19,
        name: "親子料理教室「季節の和食を作ろう」",
        date: "2025-12-14",
        time: "10:00~13:00",
        category: "子育て・教育",
        venue: "平城公民館",
        address: "奈良県奈良市秋篠町1468",
        lat: 34.706211,
        lon: 135.777631,
        description: "親子で季節の和食作りを体験。事前申込制。保育サービス（6か月〜就学前、要事前申込）あり。",
        accessibility: ["多目的トイレ", "車椅子貸出", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "平城公民館 0742-48-3578",
        capacity: "12組",
        fee: "材料費800円"
    },
    {
        id: 20,
        name: "シニアのためのスマートフォン教室（基礎編）",
        date: "2025-12-05",
        time: "13:30~15:30",
        category: "IT・デジタル",
        venue: "奈良市北部会館",
        address: "奈良県奈良市右京1丁目1-4",
        lat: 34.707524,
        lon: 135.783516,
        description: "スマートフォンの基本操作を学ぶ教室。LINE、カメラ、地図アプリなどの使い方を解説。事前申込制。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応", "車椅子貸出", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市北部会館 0742-71-5747",
        capacity: "20名",
        fee: "無料（要事前申込）"
    },
    {
        id: 21,
        name: "健康体操教室「楽しく動いて元気になろう」",
        date: "2025-12-10",
        time: "10:00~11:30",
        category: "健康・福祉",
        venue: "はぐくみセンター2階",
        address: "奈良県奈良市三条本町13-1",
        lat: 34.682551,
        lon: 135.820267,
        description: "シニア向けの健康体操教室。無理なく身体を動かして健康維持。事前申込制。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応", "車椅子貸出", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市健康増進課 0742-34-5129",
        capacity: "30名",
        fee: "無料"
    },
    {
        id: 22,
        name: "児童虐待・DV防止相談会",
        date: "2025-11-15",
        time: "10:00~16:00",
        category: "子育て・福祉",
        venue: "子ども未来部 子育て相談課",
        address: "奈良県奈良市二条大路南1-1-1",
        lat: 34.687217,
        lon: 135.809463,
        description: "児童虐待やDVに関する相談会。電話、Web、チャット、FAXなど多様な相談方法あり。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "子ども・子育て相談ダイヤル 0742-34-4804",
        capacity: "制限なし",
        fee: "無料"
    },
    {
        id: 23,
        name: "地域防災セミナー「災害に備えよう」",
        date: "2025-12-18",
        time: "13:30~15:30",
        category: "防災・安全",
        venue: "奈良市防災センター",
        address: "奈良県奈良市八条5丁目404-1",
        lat: 34.656912,
        lon: 135.812345,
        description: "地震や水害などの災害への備えを学ぶセミナー。家庭でできる防災対策や避難行動を解説。",
        accessibility: ["多目的トイレ", "段差への対応", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市危機管理課 0742-34-4930",
        capacity: "50名",
        fee: "無料（要事前申込）"
    },
    {
        id: 24,
        name: "手作り雑貨マーケット",
        date: "2025-12-22",
        time: "11:00~16:00",
        category: "文化・イベント",
        venue: "ならまちセンター広場",
        address: "奈良県奈良市東寺林町38",
        lat: 34.677851,
        lon: 135.831223,
        description: "地元作家による手作り雑貨やアクセサリーの販売。クリスマスプレゼントにもおすすめ。",
        accessibility: ["多目的トイレ", "段差への対応", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "ならまちセンター 0742-27-1151",
        capacity: "制限なし",
        fee: "入場無料"
    },
    {
        id: 25,
        name: "奈良の歴史探訪ウォーク",
        date: "2026-01-18",
        time: "09:30~15:00",
        category: "文化・観光",
        venue: "奈良市内各所（集合:近鉄奈良駅前）",
        address: "奈良県奈良市東向中町29",
        lat: 34.681591,
        lon: 135.829163,
        description: "ガイド付きで奈良の歴史的名所を巡るウォーキングツアー。約6kmのコース。",
        accessibility: ["段差への対応", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市観光協会 0742-22-3900",
        capacity: "30名",
        fee: "500円（要事前申込）"
    },
    {
        id: 26,
        name: "新春書き初め大会",
        date: "2026-01-08",
        time: "10:00~12:00",
        category: "文化・イベント",
        venue: "奈良市北部会館",
        address: "奈良県奈良市右京1丁目1-4",
        lat: 34.707524,
        lon: 135.783516,
        description: "新春の書き初め大会。小学生から大人まで参加可能。書道道具の貸出あり。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応", "車椅子貸出", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市北部会館 0742-71-5747",
        capacity: "50名",
        fee: "材料費300円"
    },
    {
        id: 27,
        name: "冬の星空観察会",
        date: "2026-01-24",
        time: "18:30~20:30",
        category: "科学・自然",
        venue: "奈良市青少年野外活動センター",
        address: "奈良県奈良市阪原町25-1",
        lat: 34.753642,
        lon: 135.897321,
        description: "冬の星座を観察する天体観測会。天体望遠鏡を使った観測体験あり。",
        accessibility: ["盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市青少年野外活動センター 0742-93-0029",
        capacity: "40名",
        fee: "大人300円、子ども200円（要事前申込）"
    },
    {
        id: 28,
        name: "福祉機器展示・相談会",
        date: "2026-02-12",
        time: "10:00~15:00",
        category: "健康・福祉",
        venue: "奈良市総合福祉センター",
        address: "奈良県奈良市左京5-3-1",
        lat: 34.711245,
        lon: 135.781891,
        description: "最新の福祉機器の展示と、専門家による福祉相談。介護や障害者支援の情報提供。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応", "車椅子貸出", "盲導犬・介助犬・聴導犬同伴可"],
        contact: "奈良市福祉政策課 0742-34-4593",
        capacity: "制限なし",
        fee: "無料"
    }
];

// 駅のバリアフリー情報（③最寄り駅候補選択機能で使用）
const STATIONS_DATA = [
    {
        id: 1,
        name: "学研奈良登美ヶ丘",
        line: "近鉄けいはんな線",
        operator: "近鉄",
        lat: 34.717037,
        lon: 135.781319,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true,
            braille_blocks: true,
            audio_guidance: true,
            staff_support: true
        }
    },
    {
        id: 2,
        name: "近鉄奈良",
        line: "近鉄奈良線",
        operator: "近鉄",
        lat: 34.681591,
        lon: 135.829163,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: true,
            service_dog_allowed: true,
            braille_blocks: true,
            audio_guidance: true,
            staff_support: true
        }
    },
    {
        id: 3,
        name: "新大宮",
        line: "近鉄奈良線",
        operator: "近鉄",
        lat: 34.687824,
        lon: 135.808167,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true,
            braille_blocks: true,
            audio_guidance: true,
            staff_support: true
        }
    },
    {
        id: 4,
        name: "奈良",
        line: "JR関西本線・桜井線・奈良線",
        operator: "JR西日本",
        lat: 34.680714,
        lon: 135.819916,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: true,
            service_dog_allowed: true,
            braille_blocks: true,
            audio_guidance: true,
            staff_support: true
        }
    },
    {
        id: 5,
        name: "大和西大寺",
        line: "近鉄奈良線・橿原線・京都線",
        operator: "近鉄",
        lat: 34.694912,
        lon: 135.780563,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: true,
            service_dog_allowed: true,
            braille_blocks: true,
            audio_guidance: true,
            staff_support: true
        }
    },
    {
        id: 6,
        name: "学園前",
        line: "近鉄奈良線",
        operator: "近鉄",
        lat: 34.692745,
        lon: 135.771912,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true,
            braille_blocks: true,
            audio_guidance: true,
            staff_support: true
        }
    },
    {
        id: 7,
        name: "菖蒲池",
        line: "近鉄奈良線",
        operator: "近鉄",
        lat: 34.689412,
        lon: 135.765891,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true,
            braille_blocks: true,
            audio_guidance: false,
            staff_support: true
        }
    },
    {
        id: 8,
        name: "富雄",
        line: "近鉄奈良線",
        operator: "近鉄",
        lat: 34.684123,
        lon: 135.735461,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true,
            braille_blocks: true,
            audio_guidance: true,
            staff_support: true
        }
    },
    {
        id: 9,
        name: "平城",
        line: "近鉄京都線",
        operator: "近鉄",
        lat: 34.716234,
        lon: 135.785623,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true,
            braille_blocks: true,
            audio_guidance: false,
            staff_support: true
        }
    },
    {
        id: 10,
        name: "高の原",
        line: "近鉄京都線",
        operator: "近鉄",
        lat: 34.762134,
        lon: 135.790812,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: true,
            service_dog_allowed: true,
            braille_blocks: true,
            audio_guidance: true,
            staff_support: true
        }
    }
];

// データのエクスポート
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { EVENTS_DATA, STATIONS_DATA };
}
