// イベントデータ
const EVENTS_DATA = [
    {
        id: 1,
        name: "奈良公園歴史ウォーク",
        date: "2024-12-20",
        time: "10:00-12:00",
        category: "文化",
        venue: "奈良公園",
        address: "奈良市雑司町469",
        latitude: 34.6851,
        longitude: 135.8049,
        description: "バリアフリーに配慮した奈良公園の歴史散策ツアーです。車椅子でも参加可能なルートを案内します。",
        accessibility: ["多目的トイレ", "段差への対応"],
        contact: "0742-22-0375",
        capacity: "30名",
        fee: "無料"
    },
    {
        id: 2,
        name: "シニア向けスマホ教室",
        date: "2024-12-22",
        time: "14:00-16:00",
        category: "教育",
        venue: "奈良市中部公民館",
        address: "奈良市上三条町23-4",
        latitude: 34.6826,
        longitude: 135.8266,
        description: "初心者向けのスマートフォン操作講座。大きな文字表示と音声案内で丁寧に指導します。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応"],
        contact: "0742-26-6506",
        capacity: "20名",
        fee: "500円"
    },
    {
        id: 3,
        name: "親子クッキング教室",
        date: "2024-12-25",
        time: "10:00-13:00",
        category: "子育て",
        venue: "奈良市西部公民館",
        address: "奈良市学園南三丁目1-5",
        latitude: 34.6639,
        longitude: 135.7836,
        description: "車椅子対応のキッチンで楽しく料理体験。親子で参加できるバリアフリー教室です。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応", "車椅子貸出"],
        contact: "0742-44-0101",
        capacity: "10組",
        fee: "1,000円"
    },
    {
        id: 4,
        name: "健康体操講座",
        date: "2024-12-27",
        time: "13:00-15:00",
        category: "健康",
        venue: "奈良市保健所・教育総合センター",
        address: "奈良市三条本町13-1",
        latitude: 34.6808,
        longitude: 135.8267,
        description: "座ったままできる体操から、バリアフリー対応の運動プログラムまで。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応"],
        contact: "0742-34-2303",
        capacity: "30名",
        fee: "無料"
    },
    {
        id: 5,
        name: "陶芸体験教室",
        date: "2024-12-28",
        time: "10:00-12:00",
        category: "文化",
        venue: "奈良市東部公民館",
        address: "奈良市大柳生町3633",
        latitude: 34.6372,
        longitude: 135.8976,
        description: "車椅子対応の作業台で陶芸体験。初心者大歓迎です。",
        accessibility: ["多目的トイレ"],
        contact: "0742-93-0400",
        capacity: "15名",
        fee: "1,500円"
    },
    {
        id: 6,
        name: "バドミントン体験会",
        date: "2025-01-10",
        time: "14:00-16:00",
        category: "スポーツ",
        venue: "奈良市中央体育館",
        address: "奈良市法蓮佐保山四丁目1-3",
        latitude: 34.6949,
        longitude: 135.8234,
        description: "車椅子バドミントン体験も可能。バリアフリー設備完備の体育館です。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応"],
        contact: "0742-24-1501",
        capacity: "40名",
        fee: "500円"
    },
    {
        id: 7,
        name: "絵本読み聞かせ会",
        date: "2025-01-12",
        time: "10:30-11:30",
        category: "子育て",
        venue: "奈良市立中央図書館",
        address: "奈良市東寺林町38",
        latitude: 34.6795,
        longitude: 135.8302,
        description: "バリアフリー対応の会場で、親子で楽しめる読み聞かせイベント。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応"],
        contact: "0742-26-6101",
        capacity: "20組",
        fee: "無料"
    },
    {
        id: 8,
        name: "書道体験講座",
        date: "2025-01-15",
        time: "13:00-15:00",
        category: "文化",
        venue: "奈良市北部会館市民文化ホール",
        address: "奈良市右京一丁目1-4",
        latitude: 34.7073,
        longitude: 135.7865,
        description: "車椅子対応のテーブルで書道体験。初心者から経験者まで楽しめます。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応"],
        contact: "0742-71-5747",
        capacity: "20名",
        fee: "800円"
    },
    {
        id: 9,
        name: "地域防災訓練",
        date: "2025-01-18",
        time: "10:00-12:00",
        category: "安全",
        venue: "奈良市立佐保小学校",
        address: "奈良市法蓮町802-1",
        latitude: 34.6917,
        longitude: 135.8294,
        description: "車椅子利用者も参加できる避難訓練。バリアフリー避難経路の確認もあります。",
        accessibility: ["多目的トイレ", "段差への対応"],
        contact: "0742-33-5607",
        capacity: "制限なし",
        fee: "無料"
    },
    {
        id: 10,
        name: "プロバスケ観戦イベント",
        date: "2025-01-20",
        time: "15:00-17:00",
        category: "スポーツ",
        venue: "奈良市中央体育館",
        address: "奈良市法蓮佐保山四丁目1-3",
        latitude: 34.6949,
        longitude: 135.8234,
        description: "車椅子観戦席完備。バリアフリー対応のプロバスケットボール観戦イベント。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応", "車椅子貸出"],
        contact: "0742-24-1501",
        capacity: "100名",
        fee: "1,500円"
    },
    {
        id: 11,
        name: "シニア向け健康講座",
        date: "2025-01-22",
        time: "14:00-16:00",
        category: "健康",
        venue: "奈良市南部公民館",
        address: "奈良市山町27-1",
        latitude: 34.6584,
        longitude: 135.8181,
        description: "栄養士と理学療法士による健康講座。車椅子での参加も可能です。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応"],
        contact: "0742-62-5931",
        capacity: "40名",
        fee: "無料"
    },
    {
        id: 12,
        name: "自然観察会",
        date: "2025-01-25",
        time: "10:00-12:00",
        category: "環境",
        venue: "平城宮跡歴史公園",
        address: "奈良市二条大路南三丁目5-1",
        latitude: 34.6914,
        longitude: 135.7951,
        description: "バリアフリー対応の遊歩道で自然観察。車椅子でも参加できます。",
        accessibility: ["多目的トイレ", "段差への対応"],
        contact: "0742-36-8780",
        capacity: "25名",
        fee: "無料"
    },
    {
        id: 13,
        name: "音楽コンサート",
        date: "2025-01-28",
        time: "14:00-16:00",
        category: "文化",
        venue: "奈良市北部会館市民文化ホール",
        address: "奈良市右京一丁目1-4",
        latitude: 34.7073,
        longitude: 135.7865,
        description: "車椅子席完備のコンサートホール。補聴システムも利用可能です。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応", "車椅子貸出"],
        contact: "0742-71-5747",
        capacity: "200名",
        fee: "2,000円"
    },
    {
        id: 14,
        name: "お正月飾り作り体験",
        date: "2024-12-18",
        time: "13:00-15:00",
        category: "文化",
        venue: "奈良市中部公民館",
        address: "奈良市上三条町23-4",
        latitude: 34.6826,
        longitude: 135.8266,
        description: "座ったまま作業できるテーブル配置。誰でも参加できるお正月飾り作りです。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応"],
        contact: "0742-26-6506",
        capacity: "25名",
        fee: "1,000円"
    },
    {
        id: 15,
        name: "デジタルアート展示会",
        date: "2025-02-01",
        time: "10:00-17:00",
        category: "文化",
        venue: "奈良県文化会館",
        address: "奈良市登大路町6-2",
        latitude: 34.6853,
        longitude: 135.8286,
        description: "最新のデジタルアート展示。全館バリアフリー対応の展示会場です。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応"],
        contact: "0742-23-8921",
        capacity: "制限なし",
        fee: "800円"
    },
    {
        id: 16,
        name: "認知症予防講座",
        date: "2025-02-05",
        time: "13:00-15:00",
        category: "健康",
        venue: "奈良市西部公民館",
        address: "奈良市学園南三丁目1-5",
        latitude: 34.6639,
        longitude: 135.7836,
        description: "専門医による認知症予防の講演。質疑応答の時間も設けています。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応"],
        contact: "0742-44-0101",
        capacity: "50名",
        fee: "無料"
    },
    {
        id: 17,
        name: "こども科学実験教室",
        date: "2025-02-08",
        time: "10:00-12:00",
        category: "教育",
        venue: "奈良市東部公民館",
        address: "奈良市大柳生町3633",
        latitude: 34.6372,
        longitude: 135.8976,
        description: "車椅子でも参加できる実験テーブル配置。親子で楽しめる科学実験です。",
        accessibility: ["多目的トイレ"],
        contact: "0742-93-0400",
        capacity: "15組",
        fee: "500円"
    },
    {
        id: 18,
        name: "春の花植え体験",
        date: "2025-02-12",
        time: "10:00-12:00",
        category: "環境",
        venue: "奈良市中央体育館",
        address: "奈良市法蓮佐保山四丁目1-3",
        latitude: 34.6949,
        longitude: 135.8234,
        description: "車椅子でも参加できる花壇づくり。高さ調整可能な作業台を用意しています。",
        accessibility: ["多目的トイレ", "エレベータ", "段差への対応"],
        contact: "0742-24-1501",
        capacity: "30名",
        fee: "無料"
    }
];

// 鉄道駅データ（バリアフリー情報付き）
const STATIONS_DATA = [
    {
        id: 1,
        name: "学研奈良登美ヶ丘",
        line: "けいはんな線",
        operator: "近畿日本鉄道",
        latitude: 34.7313,
        longitude: 135.7883,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true
        }
    },
    {
        id: 2,
        name: "近鉄奈良",
        line: "奈良線",
        operator: "近畿日本鉄道",
        latitude: 34.6828,
        longitude: 135.8299,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true
        }
    },
    {
        id: 3,
        name: "新大宮",
        line: "奈良線",
        operator: "近畿日本鉄道",
        latitude: 34.6877,
        longitude: 135.8138,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true
        }
    },
    {
        id: 4,
        name: "大和西大寺",
        line: "橿原線",
        operator: "近畿日本鉄道",
        latitude: 34.6933,
        longitude: 135.7833,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true
        }
    },
    {
        id: 5,
        name: "学園前",
        line: "奈良線",
        operator: "近畿日本鉄道",
        latitude: 34.6883,
        longitude: 135.7666,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: false,
            wheelchair_rental: false,
            service_dog_allowed: true
        }
    },
    {
        id: 6,
        name: "菖蒲池",
        line: "奈良線",
        operator: "近畿日本鉄道",
        latitude: 34.6899,
        longitude: 135.7777,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true
        }
    },
    {
        id: 7,
        name: "富雄",
        line: "奈良線",
        operator: "近畿日本鉄道",
        latitude: 34.6966,
        longitude: 135.7599,
        accessibility: {
            multipurpose_toilet: true,
            elevator: false,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true
        }
    },
    {
        id: 8,
        name: "平城",
        line: "京都線",
        operator: "近畿日本鉄道",
        latitude: 34.7116,
        longitude: 135.7916,
        accessibility: {
            multipurpose_toilet: false,
            elevator: false,
            barrier_free: false,
            wheelchair_rental: false,
            service_dog_allowed: false
        }
    },
    {
        id: 9,
        name: "高の原",
        line: "京都線",
        operator: "近畿日本鉄道",
        latitude: 34.7616,
        longitude: 135.7733,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true
        }
    },
    {
        id: 10,
        name: "奈良",
        line: "関西本線",
        operator: "JR西日本",
        latitude: 34.6808,
        longitude: 135.8202,
        accessibility: {
            multipurpose_toilet: true,
            elevator: true,
            barrier_free: true,
            wheelchair_rental: false,
            service_dog_allowed: true
        }
    }
];
